url: https://cionescu.github.io
baseurl: ""

# Site settings
title: Catalin Ionescu
description: Freelance Full-Stack Software Engineer with a passion for data. How can I help you?
keywords: ruby on rails consultant, looker consultant
